version: "3"
services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: cadastro-api
        ports:
            - "8001-8099:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - mup_network
    db:
        image: mysql:8.0
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: sr_cadastro
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - ./docker:/etc/mysql/conf.d
            - microservice-persistent:/var/lib/mysql
        networks:
            - mup_network
        # avoid db issue db_1          | mbind: Operation not permitted
        security_opt:
            - seccomp:unconfined
        restart: always
    supervisor:
        container_name: supervisor
        build:
            context: ./
            dockerfile: docker/supervisor/Dockerfile.supervisor
        restart: unless-stopped
        environment:
            - APP_ROOT=/var/www/html
            - QUEUE_DRIVER=${QUEUE_CONNECTION}
            - OPTIONS=${QUEUE_OPTIONS}
            - NUM_PROCS=${NUM_PROCS}
        networks:
             - mup_network
        depends_on:
            - app
            - db
volumes:
    microservice-persistent:
networks:
    mup_network:
        name: mup_network
