version: "3"
services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: cadastro-api
        ports:
            - "8001-8099:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - microservice-networks
    db:
        image: mysql:8.0
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: sr_cadastro
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - ./docker:/etc/mysql/conf.d
            - microservice-persistent:/var/lib/mysql
        networks:
            - microservice-networks
        # avoid db issue db_1          | mbind: Operation not permitted
        security_opt:
            - seccomp:unconfined
        restart: always
volumes:
    microservice-persistent:
networks:
    microservice-networks:
        driver: bridge
